### ISSUE TITLE
how to assemble genomes with four fasta files?

### ISSUE THREAD

**Issue by hongzhonglu** [StephenFordham/BacGenomePipeline#1]
HI @StephenFordham 
Very nice toolbox. Could I ask one question about the input for the genome assembly? Here, for one strain, we have four fasta files? Could we still use your nice toolbox?

<img width="383" alt="Screenshot 2021-03-05 at 14 30 07" src="https://user-images.githubusercontent.com/31989005/110122110-7def6a80-7dbf-11eb-85e6-b765b6744db6.png">

Thanks a lot!

Best regards,
Hongzhong

**Comment by StephenFordham** [comment]
Hi,
Thanks for your message.
I would suggest concatenating your fastq files into one file, such as:

(Then use bigfile.fastq as the input file)

cat *.fastq > bigfile.fastq

**Comment by hongzhonglu** [comment]
Thanks a lot! It seems that L1 and L2 mean this sample was sequenced on different lanes. L1_1 and L1_2 mean two-paired sequence. So in this case still need to concatenate fastq files into one file?

**Comment by StephenFordham** [comment]
The pipeline has only been tested on oxford nanopore long reads, its a long-read only genome assembly pipeline, so won't work with illumia reads. In the case that you are sequencing a single strain and have ONT long reads, I would recommend concatenating into one file via the terminal. If you have illumia reads I can suggest genome assembly via SPADES

**Comment by hongzhonglu** [comment]
Great thanks!

**Comment by StephenFordham** [comment]
No problem, got luck with your sequencing!
